baseURL = 'https://superstas.dev/'
languageCode = 'en-us'
title = "Stas Afanasev"
theme = 'black-and-light-fork'
publishDir = 'docs'


pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Stas Afanasev"
  disableWebFonts = true

[[menu.main]]
    name = "About"
    url  = "/"
[[menu.main]]
    name = "CV"
    url  = "/"
